pex_binary(
  name = 'linty_fresh',
  srcs = ['main.py'],
  deps = [
    '//linty_fresh/linters:linters',
    '//linty_fresh/models:models',
    '//linty_fresh/reporters:reporters',
  ],
  interpreter = 'python3.5'
)
