repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: requirements-txt-fixer
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.6.4
  #   hooks:
  #     - id: isort
  # - repo: https://github.com/ambv/black
  #   rev: 20.8b1
  #   hooks:
  #     - id: black
  #       language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.3
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  # - repo: https://github.com/pre-commit/pygrep-hooks
  #   rev: v1.6.0
  #   hooks:
  #     - id: python-check-blanket-noqa
  #     - id: python-check-mock-methods
  #     - id: python-no-log-warn
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.790
  #   hooks:
  #     - id: mypy
  #       args: [--strict, --ignore-missing-imports]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--ignore, E501]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
      - id: shellcheck
