pex_library(
  name = "reporters",
  srcs = ["github_reporter.py"],
  deps = [
    "//linty_fresh/models:models",
    "//third_party:aiohttp",
    "//third_party:typing"
  ],
  visibility = ["//visibility:public"]
)
