pex_pytest(
  name = 'reporters',
  srcs = glob(['test_*.py']),
  deps = [
    '//linty_fresh/reporters:reporters',
    '//tests/utils:utils'
  ],
  interpreter = 'python3.5',
  reqs = [
      'mock>=1.0.1'
  ]
)
